In [2]:
import numpy as np
a=np.arange(10)
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [9]:
a=np.arange(10)
b=a[::2].copy()
np.shares_memory(a,b)


False

In [12]:
a=np.array([1,2,3,4])
a+1
b=np.ones(4)+1
a-b
a*b

array([2., 4., 6., 8.])

In [13]:
c=np.diag([1,2,3,4])
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [15]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a==b
a>b

array([False, False,  True, False])

In [16]:
a=np.arange(5)
np.log(a)

C:\Users\HARSHA LAL\AppData\Local\Temp\ipykernel_8696\3044309250.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [17]:
a=np.arange(5)
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [18]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [19]:
a=np.array([1,2,3,4])
np.sum(a)

10

In [23]:
x=np.array([[1,2],[3,4]])
x
x.sum(axis=0)
x.min()
x.argmin()

0

In [25]:
a=np.tile(np.arange(0,40,10),(3,2))
a

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])