In [7]:
import numpy as np
a= np.array([0,1,2,3,4])
print(a)
print(np.arange(10))
a.ndim
a.shape
len(a)

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


5

In [4]:
a=np.arange(1000)
%timeit a**2

1.1 µs ± 5.56 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
b=np.array([[0,1,2],[3,4,5]])
b
b.ndim
a= np.diag([1,2,3,4,5])
a
np.diag(a)

array([1, 2, 3, 4, 5])

In [20]:
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
a=np.random.rand(5)
a

array([0.009439  , 0.14085795, 0.5044378 , 0.41611843, 0.05969835])

In [22]:
a=np.random.randn(5)
a

array([-1.62890869, -2.25464615, -0.41436401,  1.28798112,  0.20712765])

In [24]:
a=np.arange(10)
a.dtype
print(a[5])

5


In [25]:
b=np.array([[0,1,2],[3,4,5]])
b
print(b[1,1])

4


In [26]:
a=np.arange(10)
a[1:8:2]

array([1, 3, 5, 7])

In [49]:
a=np.arange(10)
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

AttributeError: module 'numpy' has no attribute 'share_memory'

In [41]:
a=np.random.randint(0,20,15)
a

array([ 9,  4, 19, 11,  1,  3, 12, 11,  7, 16, 18, 18, 15, 16,  5])

In [55]:
mask=(a%2==0)
c=a[mask]
a[mask]=-1
a

array([-1,  1, -1,  3, -1, -1,  3, -1,  1, -1])